#!/usr/bin/env bash
# field-genesis.sh — Environment-derived genesis script
# Auto-generates BLACKBOARD.md + initial S-001 signal from project environment.
# Called by field-arrive.sh when no BLACKBOARD and no active signals exist.
# Pure environment sensing — requires no human input.
# Failure is silent — does not block arrive flow.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
source "${SCRIPT_DIR}/field-lib.sh"

log_info "=== Genesis sequence starting ==="

# ── Step 1: Detect project type ──────────────────────────────────────

project_type="unknown"
project_lang=""
build_tool=""

if [ -f "${PROJECT_ROOT}/ProjectSettings/ProjectVersion.txt" ] || [ -d "${PROJECT_ROOT}/Assets" ]; then
  project_type="unity"; project_lang="C#"; build_tool="Unity Editor"
elif [ -f "${PROJECT_ROOT}/package.json" ]; then
  project_type="node"; project_lang="JavaScript/TypeScript"
  if [ -f "${PROJECT_ROOT}/yarn.lock" ]; then build_tool="yarn"
  elif [ -f "${PROJECT_ROOT}/pnpm-lock.yaml" ]; then build_tool="pnpm"
  else build_tool="npm"; fi
elif [ -f "${PROJECT_ROOT}/requirements.txt" ] || [ -f "${PROJECT_ROOT}/pyproject.toml" ] || [ -f "${PROJECT_ROOT}/setup.py" ]; then
  project_type="python"; project_lang="Python"
  if [ -f "${PROJECT_ROOT}/pyproject.toml" ]; then build_tool="pyproject"
  elif [ -f "${PROJECT_ROOT}/Pipfile" ]; then build_tool="pipenv"
  else build_tool="pip"; fi
elif [ -f "${PROJECT_ROOT}/go.mod" ]; then
  project_type="go"; project_lang="Go"; build_tool="go"
elif [ -f "${PROJECT_ROOT}/Cargo.toml" ]; then
  project_type="rust"; project_lang="Rust"; build_tool="cargo"
elif [ -f "${PROJECT_ROOT}/pom.xml" ] || [ -f "${PROJECT_ROOT}/build.gradle" ] || [ -f "${PROJECT_ROOT}/build.gradle.kts" ]; then
  project_type="java"; project_lang="Java"
  if [ -f "${PROJECT_ROOT}/build.gradle" ] || [ -f "${PROJECT_ROOT}/build.gradle.kts" ]; then build_tool="gradle"
  else build_tool="maven"; fi
elif [ -f "${PROJECT_ROOT}/Gemfile" ]; then
  project_type="ruby"; project_lang="Ruby"; build_tool="bundler"
elif [ -f "${PROJECT_ROOT}/mix.exs" ]; then
  project_type="elixir"; project_lang="Elixir"; build_tool="mix"
elif [ -f "${PROJECT_ROOT}/Makefile" ]; then
  project_type="make"; build_tool="make"
fi

log_info "Detected project type: ${project_type} (${project_lang:-unknown lang}, ${build_tool:-unknown tool})"

# ── Step 2: Extract work direction from git log ─────────────────────

git_summary=""
if git -C "$PROJECT_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  recent_commits=$(git -C "$PROJECT_ROOT" log --oneline -n 20 --no-merges 2>/dev/null || true)
  if [ -n "$recent_commits" ]; then
    # Extract most common words from commit messages (excluding common words)
    git_summary=$(echo "$recent_commits" | sed 's/^[a-f0-9]* //' | head -5)
  fi
fi

# ── Step 3: Extract project description from README ─────────────────

readme_desc=""
for readme in README.md readme.md README.rst README.txt README; do
  if [ -f "${PROJECT_ROOT}/${readme}" ]; then
    readme_desc=$(head -50 "${PROJECT_ROOT}/${readme}" 2>/dev/null | grep -v '^#' | grep -v '^$' | head -3 | tr '\n' ' ' | head -c 200)
    break
  fi
done

# ── Step 4: Generate BLACKBOARD.md skeleton ──────────────────────────

if [ -f "$BLACKBOARD" ]; then
  log_info "BLACKBOARD.md already exists — skipping generation"
else
  project_name=$(basename "$PROJECT_ROOT")

  cat > "$BLACKBOARD" <<BBEOF
# BLACKBOARD.md — ${project_name}

> Auto-generated by field-genesis.sh on $(today_iso). Verify and refine.

## Project Summary

- **Type**: ${project_type} (${project_lang:-unknown})
- **Build Tool**: ${build_tool:-unknown}
${readme_desc:+- **Description**: ${readme_desc}}

## Colony Health

| Dimension | Status | Trend | Last Verified |
|-----------|--------|-------|---------------|
| Build     | ?      | —     | unverified    |
| Tests     | ?      | —     | unverified    |
| Docs      | ?      | —     | unverified    |

## Signals

| ID | Type | Title | Weight | TTL | Status | Owner |
|----|------|-------|--------|-----|--------|-------|

## Hotspot Areas

(none)

## Notes for AI

${git_summary:+Recent work direction:
$(echo "$git_summary" | sed 's/^/- /')}

## Known Limitations

(none — genesis session, pending first verification)

## Immune Log

(none)
BBEOF

  log_info "Generated BLACKBOARD.md for ${project_name}"
fi

# ── Step 5: Generate initial S-001 signal ─────────────────────────────

# Derive title from README or project type
explore_title=""
if [ -n "$readme_desc" ]; then
  explore_title="Map project: $(echo "$readme_desc" | head -c 60)"
elif [ -n "$git_summary" ]; then
  explore_title="Map project: $(echo "$git_summary" | head -1 | head -c 60)"
else
  explore_title="Map ${project_type} project — verify build, test, document structure"
fi

if has_db; then
  source "${SCRIPT_DIR}/termite-db.sh"
  existing=$(db_signal_count "status NOT IN ('archived')" 2>/dev/null || echo "0")
  if [ "$existing" -eq 0 ]; then
    signal_id=$(db_next_signal_id "S")
    db_signal_create "$signal_id" "EXPLORE" "$explore_title" "open" 35 "$EXPLORE_MAX_DAYS" \
      "$(today_iso)" "$(today_iso)" "unassigned" "project-root" "[genesis, explore]" \
      "Run build/test, map directory structure, refine BLACKBOARD.md" 0 "autonomous"
    log_info "Generated ${signal_id}: ${explore_title} (DB)"
  else
    log_info "Active signals already exist — skipping signal generation"
  fi
else
  ensure_signal_dirs

  if [ "$(count_active_signals 2>/dev/null || echo 0)" -eq 0 ]; then
    signal_id=$(next_signal_id S)
    signal_file="${ACTIVE_DIR}/${signal_id}.yaml"

    cat > "$signal_file" <<SIGEOF
id: ${signal_id}
type: EXPLORE
title: "${explore_title}"
status: open
weight: 35
ttl_days: ${EXPLORE_MAX_DAYS}
created: $(today_iso)
last_touched: $(today_iso)
owner: unassigned
module: "project-root"
tags: [genesis, explore]
next: "Run build/test, map directory structure, refine BLACKBOARD.md"
touch_count: 0
source: autonomous
SIGEOF

    log_info "Generated ${signal_id}: ${explore_title}"
  else
    log_info "Active signals already exist — skipping signal generation"
  fi
fi

log_info "=== Genesis sequence complete ==="
