import { describe, expect, it } from 'vitest';
import { buildIntentStarterHelperHealthView } from '@/lib/intent-starter-helper-health';

describe('intent-starter-helper-health', () => {
  it('merges starter, suppressed, capability links, and verification queue into one helper health view', () => {
    const result = buildIntentStarterHelperHealthView({
      starterHelpers: [
        {
          helper: '__e2e.observeSubmitState',
          runCount: 12,
          passedRuns: 8,
          passRate: 66.7,
          suggestedReuseRuns: 7,
          source: 'stable',
          supportingRuleIds: ['checkout.submit_state'],
          supportingRuleTitles: ['提交态收敛'],
          knowledgeChangeTier: 'watching',
          knowledgeChangeWatchingKind: 'recovering',
          knowledgeChangeSignalReason: '已观察到局部恢复，但仍需继续观察。',
          knowledgeChangeDecisionableRuleCount: 2,
          preferredPromotionStatus: 'await_more_positive_rules',
          preferredPromotionReason: '__e2e.observeSubmitState 当前长期正向已判定规则 1/2 条，尚不足以自动提级为长期优先层。',
          preferredAutoPromotionCondition:
            '至少 2 条已判定 supporting rules 转为长期正向，且负向 / 混合 signal 清零后，才自动提级为长期优先层。',
          preferredPromotionRequiredPositiveRuleCount: 2,
          preferredPromotionPositiveRuleCount: 1,
          preferredPromotionNegativeRuleCount: 0,
          recentFailedVerifyCapabilityCount: 1,
          recentFailedVerifyExecutionCount: 2,
          recommendation: '可继续复用，但暂不应当成长期强正向 starter helper 自动提级。',
        },
        {
          helper: '__e2e.openAntdDropdown',
          runCount: 10,
          passedRuns: 7,
          passRate: 70,
          suggestedReuseRuns: 6,
          source: 'stable',
          supportingRuleIds: ['checkout.dropdown'],
          supportingRuleTitles: ['来源下拉'],
          knowledgeChangeTier: 'watching',
          knowledgeChangeWatchingKind: 'mixed',
          knowledgeChangeSignalReason: '存在局部恢复，但整体仍是混合观察。',
          knowledgeChangeDecisionableRuleCount: 2,
          preferredPromotionStatus: 'blocked_by_mixed_evidence',
          preferredPromotionReason: '__e2e.openAntdDropdown 当前长期 evidence 仍呈混合信号（正向 1 条 / 负向 1 条），需先清零冲突信号后再评估提级。',
          preferredAutoPromotionCondition:
            '至少 2 条已判定 supporting rules 转为长期正向，且负向 / 混合 signal 清零后，才自动提级为长期优先层。',
          preferredPromotionRequiredPositiveRuleCount: 2,
          preferredPromotionPositiveRuleCount: 1,
          preferredPromotionNegativeRuleCount: 1,
          recentFailedReviewExecutionCount: 1,
          recommendation: '继续保守复用。',
        },
        {
          helper: '__e2e.waitForApiResponse',
          runCount: 9,
          passedRuns: 7,
          passRate: 77.8,
          suggestedReuseRuns: 8,
          source: 'promoted',
          supportingRuleIds: ['checkout.api'],
          supportingRuleTitles: ['关键接口成功'],
          knowledgeChangeSignal: 'positive',
          knowledgeChangeSignalReason: '长期效果持续偏正向。',
          knowledgeChangeDecisionableRuleCount: 3,
          recommendation: '适合作为首轮生成时优先复用的 starter helper。',
        },
      ],
      suppressedStarterHelpers: [
        {
          helper: '__e2e.clickAntdRowAction',
          runCount: 7,
          passedRuns: 2,
          passRate: 28.6,
          suggestedReuseRuns: 5,
          source: 'stable',
          supportingRuleIds: ['checkout.row_action'],
          supportingRuleTitles: ['列表行尾动作'],
          knowledgeChangeSignal: 'negative',
          knowledgeChangeSignalReason: '长期效果仍偏负向。',
          knowledgeChangeDecisionableRuleCount: 2,
          knowledgeChangeSupportingAuditIds: ['audit_row_negative'],
          governanceTargetCapabilityCount: 2,
          governanceRecommendationStatus: 'blocked_by_recent_failures',
          governanceRecommendationReason: '__e2e.clickAntdRowAction 近 14 天仍存在 helper 失败窗口未清零，继续保持 suppressed。',
          governanceAutoUnlockCondition:
            '最近失败窗口清零，且至少 2/2 条治理目标能力最新状态恢复为通过，并至少 1 条完成直接标准验证通过。',
          governanceRequiredPassedCapabilityCount: 2,
          governancePassedCapabilityCount: 1,
          governanceDirectVerifyPassedCapabilityCount: 0,
          suppressionReason: '长期效果仍偏负向。',
        },
      ],
      capabilities: [
        {
          capabilityUid: 'cap_observe',
          name: '观察提交态',
          slug: 'starter.assert.observe-submit-state',
          status: 'active',
          meta: {
            starterHelper: '__e2e.observeSubmitState',
            lastVerificationStatus: 'failed',
            lastVerificationExecutionUid: 'exec_observe_verify',
            lastVerificationAt: '2026-03-24T10:00:00.000Z',
            lastVerificationIntent: 'verify',
          },
        },
        {
          capabilityUid: 'cap_api',
          name: '关键接口成功',
          slug: 'starter.assert.wait-for-api-response',
          status: 'active',
          meta: {
            starterHelper: '__e2e.waitForApiResponse',
            lastVerificationStatus: 'passed',
            lastVerificationExecutionUid: 'exec_api_verify',
            lastVerificationAt: '2026-03-24T10:10:00.000Z',
            lastVerificationIntent: 'verify',
          },
        },
        {
          capabilityUid: 'cap_dropdown',
          name: '来源下拉稳定打开',
          slug: 'starter.ui.open-antd-dropdown',
          status: 'active',
          meta: {
            starterHelper: '__e2e.openAntdDropdown',
          },
        },
        {
          capabilityUid: 'cap_row',
          name: '列表行尾动作',
          slug: 'starter.ui.click-row-action',
          status: 'active',
          meta: {
            starterHelper: '__e2e.clickAntdRowAction',
            lastVerificationStatus: 'failed',
            lastVerificationExecutionUid: 'exec_row_review',
            lastVerificationAt: '2026-03-24T10:20:00.000Z',
            lastVerificationIntent: 'review',
          },
        },
        {
          capabilityUid: 'cap_row_archived',
          name: '旧版列表行尾动作',
          slug: 'starter.ui.click-row-action-legacy',
          status: 'archived',
          meta: {
            starterHelper: '__e2e.clickAntdRowAction',
            lastVerificationStatus: 'failed',
            lastVerificationExecutionUid: 'exec_row_archived_verify',
            lastVerificationAt: '2026-03-24T10:25:00.000Z',
            lastVerificationIntent: 'verify',
          },
        },
      ],
      verificationQueueItems: [
        {
          capabilityUid: 'cap_row',
          name: '列表行尾动作',
          starterHelper: '__e2e.clickAntdRowAction',
          recommendationKind: 'suppressed_helper_review',
          recommendedMode: 'verify',
          lastVerificationIntent: 'review',
          latestRepairObservationAt: '2026-03-24T18:01:00.000Z',
          latestRepairObservationSummary: '观察上下文：page_surface=observed',
          latestRepairObservationVerifierCheckUids: ['review_row_status'],
          promotionGraderDecision: {
            version: 1,
            inputVersion: 1,
            readiness: 'suppressed',
            kind: 'suppressed_review',
            reasonCode: 'suppressed',
            recommendationKind: 'suppressed_helper_review',
            recommendedMode: 'verify',
            verificationIntent: 'review',
            action: 'review',
            focusEligible: true,
            critical: true,
            reviewRequired: true,
            pendingPreferredPromotion: false,
            weakRecovery: false,
            highFailurePressure: false,
          },
          promotionGraderAudit: {
            version: 1,
            subject: {
              capabilityUid: 'cap_row',
              slug: 'starter.ui.click-row-action',
              name: '列表行尾动作',
              capabilityType: 'action',
            },
            originKind: 'starter_asset',
            originLabel: 'Starter Asset',
            starterHelper: '__e2e.clickAntdRowAction',
            starterHelperSource: 'stable',
            starterAssetScope: 'global_runtime',
            verificationStatus: 'knowledge_inferred',
            verificationLabel: '知识提炼',
            latestAttemptStatus: '',
            latestAttemptIntent: '',
            latestAttemptExecutionUid: '',
            latestAttemptCheckedAt: '',
            longTermSignal: 'negative',
            longTermTier: '',
            watchingKind: '',
            preferredPromotionStatus: '',
            governanceSuppressed: true,
            activeLinkedCapabilityCount: 1,
            requiredPassedCapabilityCount: 2,
            decisionableRuleCount: 2,
            supportingRuleNames: ['列表行尾动作'],
            supportingAuditIds: ['audit_row_negative'],
            readiness: 'suppressed',
            decisionKind: 'suppressed_review',
            reasonCode: 'suppressed',
            recommendationKind: 'suppressed_helper_review',
            recommendedMode: 'verify',
            verificationIntent: 'review',
            action: 'review',
            focusEligible: true,
            critical: true,
            reviewRequired: true,
            pendingPreferredPromotion: false,
            weakRecovery: false,
            highFailurePressure: false,
          },
        },
        {
          capabilityUid: 'cap_row_2',
          name: '列表行尾动作修复',
          starterHelper: '__e2e.clickAntdRowAction',
          recommendationKind: 'repair_failed',
          recommendedMode: 'repair',
          lastVerificationIntent: 'review',
          latestRepairObservationAt: '2026-03-24T18:03:00.000Z',
          latestRepairObservationSummary: '观察上下文：anchor_presence=not_found',
          latestRepairObservationVerifierCheckUids: ['review_row_detail'],
        },
        {
          capabilityUid: 'cap_observe',
          name: '观察提交态',
          starterHelper: '__e2e.observeSubmitState',
          recommendationKind: 'watching_starter_verification',
          recommendedMode: 'verify',
          latestRepairObservationAt: '2026-03-24T18:02:00.000Z',
          latestRepairObservationSummary: '观察上下文：page_surface=observed；drawer_closed=yes',
          latestRepairObservationVerifierCheckUids: ['verify_submit_state'],
          lastVerificationIntent: 'verify',
          promotionGraderDecision: {
            version: 1,
            inputVersion: 1,
            readiness: 'watching',
            kind: 'watch_verify',
            reasonCode: 'watching',
            recommendationKind: 'watching_starter_verification',
            recommendedMode: 'verify',
            verificationIntent: 'verify',
            action: 'verify',
            focusEligible: true,
            critical: false,
            reviewRequired: false,
            pendingPreferredPromotion: true,
            weakRecovery: false,
            highFailurePressure: false,
          },
          promotionGraderAudit: {
            version: 1,
            subject: {
              capabilityUid: 'cap_observe',
              slug: 'starter.assert.observe-submit-state',
              name: '观察提交态',
              capabilityType: 'assertion',
            },
            originKind: 'starter_asset',
            originLabel: 'Starter Asset',
            starterHelper: '__e2e.observeSubmitState',
            starterHelperSource: 'stable',
            starterAssetScope: 'global_runtime',
            verificationStatus: 'knowledge_inferred',
            verificationLabel: '知识提炼',
            latestAttemptStatus: 'failed',
            latestAttemptIntent: 'verify',
            latestAttemptExecutionUid: 'exec_observe_verify',
            latestAttemptCheckedAt: '2026-03-24T10:00:00.000Z',
            longTermSignal: '',
            longTermTier: 'watching',
            watchingKind: 'recovering',
            preferredPromotionStatus: 'await_more_positive_rules',
            governanceSuppressed: false,
            activeLinkedCapabilityCount: 0,
            requiredPassedCapabilityCount: 0,
            decisionableRuleCount: 2,
            supportingRuleNames: ['提交态收敛'],
            supportingAuditIds: [],
            readiness: 'watching',
            decisionKind: 'watch_verify',
            reasonCode: 'watching',
            recommendationKind: 'watching_starter_verification',
            recommendedMode: 'verify',
            verificationIntent: 'verify',
            action: 'verify',
            focusEligible: true,
            critical: false,
            reviewRequired: false,
            pendingPreferredPromotion: true,
            weakRecovery: false,
            highFailurePressure: false,
          },
        },
      ],
    });

    expect(result.summary).toMatchObject({
      totalHelpers: 4,
      preferredCount: 1,
      watchingCount: 2,
      recoveringWatchingCount: 1,
      mixedWatchingCount: 1,
      suppressedCount: 1,
      promoteReadyCount: 1,
      blockedByFailurePressureCount: 0,
      weakRecoveryCount: 0,
      governanceHelperCount: 2,
      linkedActiveCapabilityCount: 4,
      linkedArchivedCapabilityCount: 1,
      recommendedCapabilityCount: 3,
      recommendedRepairCount: 1,
      recommendedReviewCount: 1,
      promotionGraderSummary: {
        decisionCount: 2,
        focusEligibleCount: 2,
        reviewRequiredCount: 1,
        verifyActionCount: 1,
        ignoreActionCount: 0,
        criticalCount: 1,
        highFailureCount: 0,
        pendingPreferredPromotionCount: 1,
        suppressedReviewCount: 1,
        blockedReviewCount: 0,
        weakRecoveryReviewCount: 0,
        watchReviewCount: 0,
        watchVerifyCount: 1,
        promoteVerifyCount: 0,
        notApplicableCount: 0,
      },
      failurePressureSummary: {
        recentFailedReviewCapabilityCount: 2,
        recentFailedVerifyCapabilityCount: 2,
        recentFailedReviewExecutionCount: 1,
        recentFailedVerifyExecutionCount: 2,
        recentFailureWindowDays: 14,
        highFailureCandidateCount: 1,
        highFailureRepairCount: 0,
        highFailureGovernanceCount: 1,
      },
      failurePressure: {
        recentFailedReviewCapabilityCount: 2,
        recentFailedVerifyCapabilityCount: 2,
        recentFailedReviewExecutionCount: 1,
        recentFailedVerifyExecutionCount: 2,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 2,
      recentFailedVerifyCapabilityCount: 2,
    });
    expect(result.items.map((item) => item.helper)).toEqual([
      '__e2e.clickAntdRowAction',
      '__e2e.observeSubmitState',
      '__e2e.openAntdDropdown',
      '__e2e.waitForApiResponse',
    ]);
    expect(result.items[0]).toMatchObject({
      healthStatus: 'suppressed',
      promotionEvidence: {
        readiness: 'suppressed',
      },
      activeLinkedCapabilityCount: 1,
      archivedLinkedCapabilityCount: 1,
      recommendedCapabilityCount: 2,
      recommendedRepairCount: 1,
      recommendedReviewCount: 1,
      failurePressure: {
        recentFailedReviewCapabilityCount: 1,
        recentFailedVerifyCapabilityCount: 0,
        recentFailedReviewExecutionCount: 0,
        recentFailedVerifyExecutionCount: 0,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 1,
      recentFailedVerifyCapabilityCount: 0,
      recommendation: '长期效果仍偏负向。',
      governanceTargetCapabilityCount: 2,
      governanceRecommendationStatus: 'blocked_by_recent_failures',
      governanceRequiredPassedCapabilityCount: 2,
      governancePassedCapabilityCount: 1,
      governanceDirectVerifyPassedCapabilityCount: 0,
      latestRepairObservationAt: '2026-03-24T18:03:00.000Z',
      latestRepairObservationSummary: '观察上下文：anchor_presence=not_found',
      latestRepairObservationVerifierCheckUids: ['review_row_detail'],
    });
    expect(result.items[0]?.governanceRecommendationReason).toContain('失败窗口未清零');
    expect(result.items[0]?.governanceAutoUnlockCondition).toContain('至少 2/2 条治理目标能力');
    expect(result.items[0]?.queueItems[0]).toMatchObject({
      capabilityUid: 'cap_row_2',
      recommendedMode: 'repair',
      lastVerificationIntent: 'review',
    });
    expect(result.items[0]?.queueItems[1]).toMatchObject({
      capabilityUid: 'cap_row',
      promotionGraderDecision: {
        kind: 'suppressed_review',
        action: 'review',
      },
      promotionGraderAudit: {
        decisionKind: 'suppressed_review',
        governanceSuppressed: true,
        requiredPassedCapabilityCount: 2,
      },
    });
    expect(result.items[1]).toMatchObject({
      healthStatus: 'watching',
      healthLabel: '恢复观察',
      promotionEvidence: {
        readiness: 'watching',
      },
      knowledgeChangeWatchingKind: 'recovering',
      preferredPromotionStatus: 'await_more_positive_rules',
      preferredPromotionRequiredPositiveRuleCount: 2,
      preferredPromotionPositiveRuleCount: 1,
      preferredPromotionNegativeRuleCount: 0,
      recommendedCapabilityCount: 1,
      latestRepairObservationAt: '2026-03-24T18:02:00.000Z',
      latestRepairObservationSummary: '观察上下文：page_surface=observed；drawer_closed=yes',
      latestRepairObservationVerifierCheckUids: ['verify_submit_state'],
      recommendedVerificationCount: 1,
      failurePressure: {
        recentFailedReviewCapabilityCount: 0,
        recentFailedVerifyCapabilityCount: 2,
        recentFailedReviewExecutionCount: 0,
        recentFailedVerifyExecutionCount: 2,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 0,
      recentFailedVerifyCapabilityCount: 2,
    });
    expect(result.items[1]?.queueItems[0]).toMatchObject({
      capabilityUid: 'cap_observe',
      promotionGraderDecision: {
        kind: 'watch_verify',
        action: 'verify',
      },
      promotionGraderAudit: {
        decisionKind: 'watch_verify',
        pendingPreferredPromotion: true,
      },
    });
    expect(result.items[1]?.preferredPromotionReason).toContain('1/2');
    expect(result.items[1]?.preferredAutoPromotionCondition).toContain('至少 2 条已判定 supporting rules');
    expect(result.items[2]).toMatchObject({
      healthStatus: 'watching',
      healthLabel: '混合观察',
      promotionEvidence: {
        readiness: 'watching',
      },
      knowledgeChangeWatchingKind: 'mixed',
      preferredPromotionStatus: 'blocked_by_mixed_evidence',
      preferredPromotionRequiredPositiveRuleCount: 2,
      preferredPromotionPositiveRuleCount: 1,
      preferredPromotionNegativeRuleCount: 1,
      recommendedCapabilityCount: 0,
      failurePressure: {
        recentFailedReviewCapabilityCount: 1,
        recentFailedVerifyCapabilityCount: 0,
        recentFailedReviewExecutionCount: 1,
        recentFailedVerifyExecutionCount: 0,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 1,
      recentFailedVerifyCapabilityCount: 0,
    });
    expect(result.items[2]?.preferredPromotionReason).toContain('混合信号');
    expect(result.items[3]).toMatchObject({
      healthStatus: 'preferred',
      promotionEvidence: {
        readiness: 'promote_ready',
      },
      recommendedCapabilityCount: 0,
      knowledgeChangeSignal: 'positive',
      failurePressure: {
        recentFailedReviewCapabilityCount: 0,
        recentFailedVerifyCapabilityCount: 0,
        recentFailedReviewExecutionCount: 0,
        recentFailedVerifyExecutionCount: 0,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 0,
      recentFailedVerifyCapabilityCount: 0,
    });
  });

  it('keeps neutral starter helpers visible even without linked capabilities or queue items', () => {
    const result = buildIntentStarterHelperHealthView({
      starterHelpers: [
        {
          helper: '__e2e.ensureLoggedIn',
          runCount: 25,
          passedRuns: 4,
          passRate: 16,
          suggestedReuseRuns: 0,
          source: 'promoted',
          supportingRuleIds: ['auth.login'],
          supportingRuleTitles: ['统一登录'],
          recommendation: '可继续作为基础 starter helper 使用。',
        },
      ],
      suppressedStarterHelpers: [],
      capabilities: [],
      verificationQueueItems: [],
    });

    expect(result.summary).toMatchObject({
      totalHelpers: 1,
      neutralCount: 1,
      promoteReadyCount: 0,
      blockedByFailurePressureCount: 0,
      weakRecoveryCount: 0,
      governanceHelperCount: 0,
      linkedActiveCapabilityCount: 0,
      recentFailedReviewCapabilityCount: 0,
      recentFailedVerifyCapabilityCount: 0,
    });
    expect(result.items[0]).toMatchObject({
      helper: '__e2e.ensureLoggedIn',
      healthStatus: 'neutral',
      linkedCapabilities: [],
      queueItems: [],
      failurePressure: {
        recentFailedReviewCapabilityCount: 0,
        recentFailedVerifyCapabilityCount: 0,
        recentFailedReviewExecutionCount: 0,
        recentFailedVerifyExecutionCount: 0,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 0,
      recentFailedVerifyCapabilityCount: 0,
    });
  });

  it('prefers helper execution-window failure counts over linked capability latest failures when feedback exists', () => {
    const result = buildIntentStarterHelperHealthView({
      starterHelpers: [
        {
          helper: '__e2e.observeSubmitState',
          runCount: 6,
          passedRuns: 4,
          passRate: 66.7,
          suggestedReuseRuns: 3,
          source: 'stable',
          supportingRuleIds: ['checkout.submit_state'],
          supportingRuleTitles: ['提交态收敛'],
          recentFailedVerifyCapabilityCount: 1,
          recentFailedVerifyExecutionCount: 0,
          recommendation: '继续观察。',
        },
      ],
      suppressedStarterHelpers: [],
      capabilities: [
        {
          capabilityUid: 'cap_observe',
          name: '观察提交态',
          slug: 'starter.assert.observe-submit-state',
          status: 'active',
          meta: {
            starterHelper: '__e2e.observeSubmitState',
            lastVerificationStatus: 'failed',
            lastVerificationExecutionUid: 'exec_observe_verify',
            lastVerificationAt: '2026-03-24T10:00:00.000Z',
            lastVerificationIntent: 'verify',
          },
        },
      ],
      verificationQueueItems: [],
    });

    expect(result.summary.recentFailedReviewCapabilityCount).toBe(0);
    expect(result.summary.recentFailedVerifyCapabilityCount).toBe(0);
    expect(result.summary.failurePressure).toMatchObject({
      recentFailedReviewCapabilityCount: 0,
      recentFailedVerifyCapabilityCount: 0,
      recentFailedReviewExecutionCount: 0,
      recentFailedVerifyExecutionCount: 0,
      recentFailureWindowDays: 14,
    });
    expect(result.items[0]).toMatchObject({
      helper: '__e2e.observeSubmitState',
      failurePressure: {
        recentFailedReviewCapabilityCount: 0,
        recentFailedVerifyCapabilityCount: 0,
        recentFailedReviewExecutionCount: 0,
        recentFailedVerifyExecutionCount: 0,
        recentFailureWindowDays: 14,
      },
      recentFailedReviewCapabilityCount: 0,
      recentFailedVerifyCapabilityCount: 0,
    });
  });

  it('surfaces blocked and weak-recovery promotion evidence in summary and helper ordering', () => {
    const result = buildIntentStarterHelperHealthView({
      starterHelpers: [
        {
          helper: '__e2e.observeSubmitState',
          runCount: 8,
          passedRuns: 6,
          passRate: 75,
          suggestedReuseRuns: 6,
          source: 'stable',
          supportingRuleIds: ['checkout.submit_state'],
          supportingRuleTitles: ['提交态收敛'],
          knowledgeChangeSignal: 'positive',
          knowledgeChangeSignalReason: '长期效果持续偏正向。',
          knowledgeChangeDecisionableRuleCount: 3,
          recentFailedVerifyExecutionCount: 2,
          recommendation: '当前 helper 仍需止血观察。',
        },
        {
          helper: '__e2e.selectAntdOption',
          runCount: 9,
          passedRuns: 7,
          passRate: 77.8,
          suggestedReuseRuns: 7,
          source: 'stable',
          supportingRuleIds: ['checkout.select'],
          supportingRuleTitles: ['下拉选择'],
          knowledgeChangeTier: 'watching',
          knowledgeChangeWatchingKind: 'recovering',
          knowledgeChangeSignalReason: '已从治理隔离中恢复，但仍需继续观察。',
          knowledgeChangeDecisionableRuleCount: 1,
          preferredPromotionStatus: 'await_long_term_recovery',
          preferredPromotionReason: '仍需更多长期正向规则。',
          preferredAutoPromotionCondition: '至少 2 条长期正向规则转正。',
          preferredPromotionRequiredPositiveRuleCount: 2,
          preferredPromotionPositiveRuleCount: 1,
          preferredPromotionNegativeRuleCount: 0,
          governanceReleaseStatus: 'released_from_suppressed',
          governanceReleaseReason: '治理恢复后保守释放。',
          governanceReleaseCapabilityCount: 1,
          governanceReleaseDirectVerifyPassedCapabilityCount: 1,
          governanceReleaseManualRepairPassedCapabilityCount: 0,
          governanceReleaseAutoRepairPassedCapabilityCount: 1,
          governanceReleaseLatestVerifyExecutionAt: '2026-03-25T11:00:00.000Z',
          recommendation: '继续观察，不直接提级。',
        },
        {
          helper: '__e2e.waitForApiResponse',
          runCount: 10,
          passedRuns: 9,
          passRate: 90,
          suggestedReuseRuns: 8,
          source: 'promoted',
          supportingRuleIds: ['checkout.api'],
          supportingRuleTitles: ['关键接口成功'],
          knowledgeChangeSignal: 'positive',
          knowledgeChangeSignalReason: '长期效果持续偏正向。',
          knowledgeChangeDecisionableRuleCount: 3,
          recommendation: '适合作为首轮生成时优先复用的 starter helper。',
        },
      ],
      suppressedStarterHelpers: [],
      capabilities: [],
      verificationQueueItems: [],
    });

    expect(result.summary).toMatchObject({
      totalHelpers: 3,
      promoteReadyCount: 1,
      blockedByFailurePressureCount: 1,
      weakRecoveryCount: 1,
    });
    expect(result.items.map((item) => item.helper)).toEqual([
      '__e2e.observeSubmitState',
      '__e2e.selectAntdOption',
      '__e2e.waitForApiResponse',
    ]);
    expect(result.items[0]?.promotionEvidence?.readiness).toBe('blocked_by_failure_pressure');
    expect(result.items[1]?.promotionEvidence).toMatchObject({
      readiness: 'watching',
      governance: {
        weakRecovery: true,
      },
    });
    expect(result.items[2]?.promotionEvidence?.readiness).toBe('promote_ready');
  });
});
